### ISSUE TITLE
try and introduce error handling here

### ISSUE THREAD

**Issue by animeshcard91** [sparida-card91/demo-fastify-knex#2]
https://github.com/sparida-card91/demo-fastify-knex/blob/475fde4f0000a9db1b663d4bb3f176b08036db5e/controller/messages.js#L6

So check what happens if you try to access your API without the DB being up. if DB is not reachable, you will probably get a bad looking response. Instead, we'd like to respond with a proper message and http header (5xx in case of DB down would be appropriate)

**Comment by sparida-card91** [comment]
Added a global fastify error handler function with custom error message and status code 500

**Comment by sparida-card91** [comment]
Closing the issue
